#!/bin/bash
set -euo pipefail

########################################################################################################################
# Usage: script/build [upstream tag]
# Example: script/build v1.0.0.Final
# This script should only be used as a part of Shopify Build Container builds, it should not be used manually.
#
# Does the following:
# * checkout the tagged version
# * cherry-pick the shopify-build pipeline setup
# * replace the debezium version in the base docker image
# * build the new image and push to GCR
#
########################################################################################################################

APP_GROUP="apps"
APP_ENV="production"
REPO_SHOP="gcr.io/shopify-docker-images"
GCR_PATH="${REPO_SHOP}/${APP_GROUP}/${APP_ENV}/debezium"

DEFAULT_SHA=$(git rev-parse HEAD)
SHA="${BUILDKITE_COMMIT:-$DEFAULT_SHA}"

error() {
  echo -e "💩! ${1}\n" 1>&2 && exit 1
}

add_upstream() {
  if ! git remote -v | grep upstream; then
    git remote add upstream https://github.com/debezium/debezium.git
  fi
}

fetch_all() {
  git fetch --all --tags
  git fetch origin pristine-master
  git fetch origin master
}

checkout_upstream() {
  git checkout pristine-master
  git checkout ${BUILDKITE_BRANCH}
}

is_tag_unique() {
  [ -z "$(git ls-remote -t -q https://github.com/debezium/debezium | grep "${1}")" ]
}

parse_version() {
  echo "${1}" | sed 's/^v//'
}

setup_build() {
  git cherry-pick pristine-master..${BUILDKITE_COMMIT}
}

set_version() {
  local version="${1}"
  sed "s/DEBEZIUM_VERSION\ \".*\"/DEBEZIUM_VERSION\ \"${1}\"/" < Dockerfile > Dockerfile.tmp
  mv Dockerfile.tmp Dockerfile
}

build_and_push_image() {
  docker build \
    --build-arg JARS_CLOUDSMITH_TOKEN="${JARS_CLOUDSMITH_TOKEN:-''}" \
    -t "debezium" .
  docker tag debezium:latest "${GCR_PATH}":"${1}-${SHA}"
  docker push "${GCR_PATH}":"${1}-${SHA}"

  if [ "${BUILDKITE_BRANCH}" == "master" ]; then
    docker tag debezium:latest "${GCR_PATH}":"${1}"
    docker push "${GCR_PATH}":"${1}"
  fi
}

main() {
  add_upstream
  fetch_all
  checkout_upstream

  git config --global user.name "shopify-dep"
  git config --global user.email "notifications@github.com"

  local version="${1}"
  local short_version=$(parse_version "${1}")
  if [[ -z "${short_version}" ]]; then error "Unable to parse tag ${version}"; fi
  # tag must exist in upstream
  if is_tag_unique "${version}"; then error "Tag does not exist in debezium/debezium"; fi

  git branch -D tmp || true
  git switch -c tmp "${version}"
  setup_build
  set_version "${short_version}"

  build_and_push_image "${short_version}"
}

main "$@"
