#!/bin/bash
set -euox pipefail

MAVEN_VERSION=3.6.3
SHA=c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0

install_maven() {
  apt-get update && apt-get install -y wget
  wget --no-verbose -O /tmp/apache-maven-${MAVEN_VERSION}.tar.gz http://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
  echo "${SHA} /tmp/apache-maven-${MAVEN_VERSION}.tar.gz" | sha512sum -c -
  tar xzf /tmp/apache-maven-${MAVEN_VERSION}.tar.gz -C /opt/
  ln -s /opt/apache-maven-${MAVEN_VERSION} /opt/maven
  ln -s /opt/maven/bin/mvn /usr/local/bin
  rm -f /tmp/apache-maven-${MAVEN_VERSION}.tar.gz
}

if ! which mvn
then
  install_maven
fi
