#!/bin/bash
set -euo pipefail

########################################################################################################################
# Usage: script/release [upstream tag]
# Example: script/release v1.0.0.Final
#
# Does the following:
#
# * checkout the tagged version
# * cherry-pick the shopify-build pipeline setup
# * replace the debezium version in the base docker image
# * Commit the changes and push to GitHub.
#
# After that is done, buildkite will build the image and tag it with the branch name
########################################################################################################################

BRANCH=$(git rev-parse --abbrev-ref HEAD)

error() {
  echo -e "💩! ${1}\n" 1>&2 && exit 1
}

is_on_master() {
  [ "${BRANCH}" == "master" ]
}

is_git_clean() {
  # untracked files are cool, but nothing in the index waiting to be committed or changed is allowed
  git diff --exit-code && git diff --quiet --cached HEAD
}

sync_upstream() {
  git checkout pristine-master
  git pull upstream master
  git push origin pristine-master

  git checkout master
  git pull origin master
  git rebase upstream/master
  git push --force-with-lease origin master
}

is_tag_unique() {
  [ -z "$(git ls-remote -t -q | grep "${1}")" ]
}

parse_version() {
  echo "${1}" | sed 's/^v//'
}

setup_build() {
  git cherry-pick pristine-master..master
}

set_version() {
  local version="${1}"
  sed "s/DEBEZIUM_VERSION\ \".*\"/DEBEZIUM_VERSION\ \"${1}\"/" < Dockerfile > Dockerfile.tmp
  mv Dockerfile.tmp Dockerfile
}

commit_version() {
  local version="${1}"
  git add Dockerfile
  git commit -m "Bump version to ${version}"
  git push origin ${version}
}

main() {
  # make sure upstream tags are refreshed
  git fetch --all --tags

  # can only release from the master branch with a clean git index (nothing outstanding)
  if ! is_on_master;
    then error "Releases must be started from master.";
  fi
  if ! is_git_clean; then error "You need to commit or stash your changes to release"; fi

  sync_upstream

  local version="${1}"
  local short_version=$(parse_version "${1}")
  if [[ -z "${short_version}" ]]; then exit 1; fi

  # tag must exist in upstream
  if is_tag_unique "${version}"; then error "Tag does not exist in debezium/debezium"; fi

  BRANCH_NAME="${short_version}"

  git checkout "${version}" -b ${BRANCH_NAME}
  setup_build

  set_version "${short_version}"
  commit_version "${short_version}" "${BRANCH_NAME}"

  echo -e "\n🦄 Opening a PR for Releasing ${short_version} on GitHub.\n"

  open https://github.com/Shopify/debezium/compare/${BRANCH_NAME}?expand=1\&title="Build+Debezium+v${short_version}"
}

main "$@"
