#!/bin/bash
set -euox pipefail

########################################################################################################################
# Usage: script/sync_upstream
# Example: script/sync_upstream
#
# This script sync's the pristine-main branch with Debezium/Debezium main, and rebases the Shopify/Debezium main
# branch on pristine-main.
#
########################################################################################################################

BRANCH=$(git rev-parse --abbrev-ref HEAD)

error() {
  echo -e "💩! ${1}\n" 1>&2 && exit 1
}

is_on_main() {
  [ "${BRANCH}" == "main" ]
}

is_git_clean() {
  # untracked files are cool, but nothing in the index waiting to be committed or changed is allowed
  git diff --exit-code && git diff --quiet --cached HEAD
}

sync_upstream() {
  git checkout pristine-main
  git pull upstream main
  git push origin pristine-main

  git checkout main
  git pull origin main
  git rebase upstream/main
  git push --force-with-lease origin main

  # Create Shopify Specific branches for the last 10 tags
  git fetch upstream --tags
  git tag --list "v*.Final" | tail -n 10 | while read tag; do
      if git show-ref --verify --quiet "refs/heads/shopify-$tag"; then
          git branch -D shopify-$tag
          git tag -d shopify-$tag
      fi
      git checkout -b shopify-$tag $tag
      # Apply the Shopify dev/CI/release tooling commit
      git cherry-pick $(git log --oneline main | grep "Shopify dev/CI/release tooling" | cut -d' ' -f1)
      git tag shopify-$tag HEAD
      git push --force origin --tags
  done
  git checkout main
}

main() {
  # can only sync from the main branch with a clean git index (nothing outstanding)
  if ! is_on_main;
    then error "Releases must be started from main.";
  fi
  if ! is_git_clean; then error "You need to commit or stash your changes to release"; fi

  sync_upstream
}

main "$@"
